services:
  xray-core:
    image: ghcr.io/xtls/xray-core:latest
    container_name: xray-core
    restart: always
    ports:
      - "${XRAY_SERVER_IP}:${XRAY_SERVER_PORT}:443"
    #network_mode: "host" - for max speed
    #user: "0.0" - if you use host network_mode
    volumes:
      - ./config/config.json:/usr/local/etc/xray/config.json:ro
    stdin_open: true
    tty: true

  xray-subscription:
    build: .
    # image: ghcr.io/dxunvrs/xray-subscription:latest - for CI/CD
    container_name: xray-subscription
    env_file:
      - .env
    depends_on:
      - xray-core
    ports:
      - "12285:12285"
    volumes:
      - ./data/app/data
    stdin_open: true
    tty: true