services:
  xray-core:
    image: ghcr.io/xtls/xray-core:latest
    container_name: xray-core
    restart: always
    network_mode: "host"
    user: "0.0"
    environment:
      - TZ=Europe/Moscow
    volumes:
      - ./config/config.json:/usr/local/etc/xray/config.json:ro
      - /usr/share/zoneinfo/Europe/Moscow:/etc/localtime:ro
      - ./sockets:/run/xray:rw
    logging:
        driver: "json-file"
        options:
            max-size: "20m"
            max-file: "2"
    stdin_open: true
    tty: true

  xray-subscription:
    image: ghcr.io/dxunvrs/xray-subscription:feat-sockets
    container_name: xray-subscription
    env_file:
      - .env
    depends_on:
      - xray-core
    ports:
      - "12285:12285"
    volumes:
      - ./data/app/data
      - ./sockets:/run/xray:rw
    stdin_open: true
    tty: true
