spring.application.name=xray-subscription

server.port=${SERVER_PORT:12285}

spring.security.user.name=${ADMIN_USERNAME:admin}
spring.security.user.password=${ADMIN_PASSWORD:1234}

spring.datasource.url=jdbc:sqlite:./data/xray_subscriber.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

xray.grpc.target=${XRAY_GRPC_TARGET:/run/xray/api.sock}
xray.inbound.tag=${XRAY_INBOUND_TAG:vless-inbound}

xray.server.ip=${XRAY_SERVER_IP}
xray.server.port=${XRAY_SERVER_PORT}
xray.reality.publicKey=${XRAY_REALITY_PUBLIC_KEY}
xray.reality.shortId=${XRAY_REALITY_SHORT_ID}
xray.reality.sni=${XRAY_REALITY_SNI}
xray.reality.fp=${XRAY_REALITY_FINGERPRINT}

xray.stats.sync-interval=${XRAY_STATS_SYNC_INTERVAL:20m}