spring.application.name=xray-subscription

server.port=12258

spring.security.user.name=${ADMIN_USERNAME:admin}
spring.security.user.password=${ADMIN_PASSWORD:1234}

spring.datasource.url=jdbc:sqlite:xray_subscriber.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

xray.grpc.host=${XRAY_GRPC_HOST:localhost}
xray.grpc.port=${XRAY_GRPC_PORT:10085}
xray.inbound.tag=${XRAY_INBOUND_TAG:vless-inbound}

xray.server.ip=${XRAY_SERVER_IP}
xray.server.port=${XRAY_SERVER_PORT}
xray.reality.publicKey=${XRAY_REALITY_PUBLIC_KEY}
xray.reality.shortId=${XRAY_REALITY_SHORT_ID}
xray.reality.sni=${XRAY_REALITY_SNI}
xray.reality.fp=${XRAY_REALITY_FINGERPRINT}